name: Build Bonjourr server
on:
    release:
        types: [published]
    push:
        branches: ['release']
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: PadawanNico21/bonjourr-adminui
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Login to github Container Registry
              uses: docker/login-action@v3.1.0
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadatas
              id: meta
              uses: docker/metadata-action@v5.5.1
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Build and Push Image
              uses: docker/build-push-action@v5.3.0
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
